# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Get Version ID
        id: get-version-id
        run: |
          VERSION_ID=$(cat package.json | grep version | sed 's|  \"version\": \"||g' | sed 's|\",||g')
          echo "::set-output name=version-id::$(echo $VERSION_ID)"
          echo $VERSION_ID

      - name: Install and Build 🔧
        env:
          VERSION_ID: ${{ steps.get-version-id.outputs.version-id }}
        run: |
          # sed -i "s|baidu: ''|baidu: '${{ secrets.BAIDU_ANALYTICS_ID }}'|" config.ts
          pnpm i
          pnpm build

      - name: Minify HTML Index
        uses: Dup4/minify-html-action@v1
        with:
          src: './dist/index.html'

      - name: Enable 404.html
        run: |
          cp ./dist/index.html ./dist/404.html
