name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Sync
          repo: XCPCIO/XCPCIO-Board-Preview
          token: ${{ secrets.GH_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Get Version ID
        id: get-version-id
        run: |
          VERSION_ID=$(cat package.json | grep version | sed 's|  \"version\": \"||g' | sed 's|\",||g')
          echo "::set-output name=version-id::$(echo $VERSION_ID)"
          echo $VERSION_ID

      - name: Install and Build 🔧
        env:
          VERSION_ID: ${{ steps.get-version-id.outputs.version-id }}
        run: |
          sed -i "s|baidu: ''|baidu: '${{ secrets.BAIDU_ANALYTICS_ID }}'|" config.ts
          cat config.ts
          yarn
          yarn build

      - name: Minify HTML Index
        uses: Dup4/minify-html-action@v9
        with:
          src: './dist/index.html'

      - name: Enable 404.html
        run: |
          cp ./dist/index.html ./dist/404.html
