name: Sync
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64' # (x64 or x86)

      - name: Fetch and Build
        run: |
          cd scripts
          python3 get_contest_list.py
          cd ..
          cd origin-board-data
          cd ccpc
          cd 2020
          cd weihai-warmup
          pip3 install -U -r requirements.txt
          echo "" > params.json
          echo params.json
          python3 sync.py
          cd ../../../../
          npm install
          npm run build
          mkdir site
          mv dist/* site/
          mv data site/
          
      - name: Release
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            ${{ secrets.RUN_SCRIPT }}