name: Sync
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Sync
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd /var/sync
            git clone https://github.com/XCPCIO/XCPCIO-board.git
            cd XCPCIO-board/origin-board-data/ccpc/2020/weihai-warmup
            echo '${{ secrets.COKIE }}' > params.json
            python3 sync.py
            cd ../../../../
            git add .
            git commit -m "sync"
            git push
            cd ..
            rm -rf XCPCIO-board